package.json
projects/cosmoscan-extension/editions/eurx/Dockerfile
projects/cosmoscan-extension/editions/jpyx/Dockerfile
projects/cosmoscan-extension/nginx.conf
projects/cosmoscan-extension/src/app/app.component.html
projects/cosmoscan-extension/src/index.html
tsconfig.json

config付きでビルドしなくてよくなったので、jpyxつき、eurxつきのcosmoscanエクスプローラーはcosmoscanのdockerイメージからFROMして良いことに気づきましたｗ
月曜朝レビューお願いします！
（あとはresolve json importを消していいことにも気づいた）

feat: docker-optimization

---

projects/cosmoscan-extension/.gitignore

`projects/cosmoscan-extension`フォルダ内に`.gitignore`を作成、
```
#unique blockchain file
src/assets/config.js
```
を記載しています。

feat: gitignore

---

.github/workflows/docker-botany-pricefeed.yml
.github/workflows/docker-cosmoscan-eurx.yml
.github/workflows/docker-cosmoscan-jpyx.yml

DockerイメージのビルドとDocker HubへのプッシュをGitHub Actions化
```
lcnem/cosmoscan-jpyx ... docker-cosmoscan-jpyx.yml
lcnem/cosmoscan-eurx ... docker-cosmoscan-eurx.yml
lcnem/botany-pricefeed ... docker-botany-pricefeed.yml
```

feat: add-github-actions-docker-image

---

projects/cosmoscan-extension/README.md

close #32
@YasunoriMATSUOKA レビューお願いします！

docs: redme.md add of build procedure

---

.github/workflows/nodejs-website-deploy.yml

close #35 
@YasunoriMATSUOKA 
github action firebase hostingを追加しています。確認お願いします。
リリース時に実行、functionなしです。

feat: github action firebase hosting

---

package-lock.json
package.json

add  firebase tools in `/home/user/src/github.com/lcnem/botany/package.json`

fix: gihub action firebase tools

---

projects/cosmoscan-extension/editions/eurx/deploy.sh
projects/cosmoscan-extension/editions/jpyx/deploy.sh

close #44 
@KimuraYu45z 
VPS上でcosmoscanのデプロイを行う一連のコマンドをシェルスクリプトにまとめました。
レビューお願いします。

feat: cosmoscan deploy shellscript

---

.eslintrc.json

close #46
`/home/user/src/github.com/lcnem/botany/.eslintrc.json`の
```
"extends": [
"eslint:recommended",
".eslintrc.prettier.json"
```
部分を修正しています。
@YasunoriMATSUOKA 確認お願いします。

fix: ng lint error

---

.github/workflows/docker-botany-pricefeed.yml
.github/workflows/docker-cosmoscan-eurx.yml
.github/workflows/docker-cosmoscan-jpyx.yml
.vscode/extensions.json

close #30 
@YasunoriMATSUOKA 確認お願いします。

fix: github action docker build

---

.github/workflows/deploy-prod.yml

https://github.com/lcnem/botany/issues/39

feat: functionsのCD

---

.github/workflows/deploy-prod.yml

fix: docker deploy no product

---

.github/workflows/deploy-prod.yml

fix: firebase deploy

---

.github/workflows/deploy-prod.yml
functions/.eslintrc.json
functions/.prettierrc
functions/package-lock.json
functions/package.json

chore: copy from website

---

.github/workflows/docker-botany-pricefeed.yml
.github/workflows/docker-cosmoscan-eurx.yml
.github/workflows/docker-cosmoscan-jpyx.yml

@KimuraYu45z 
Docker関連のGitHub Actionsが、どれがどれのCDなのかわかりにくかったので、名前を加えました。
お手隙の際にレビューお願いします。

chore: change github actions name

---

.github/workflows/deploy-prod.yml

@YasunoriMATSUOKA `npx firebase deploy --project=default --token=${{ secrets.FIREBASE_TOKEN }}`に変更しています。
これで試してみます。

fix: firebase deploy command

---

projects/telescope-extension/editions/jpyx/config.js

@KimuraYu45z 
telescope側の、テストネット新バージョン対応の修正です。
レビューお願いします。

feat: new testnet jpyx 3 test

---

projects/telescope-extension/editions/jpyx/docker-compose.yml

@KimuraYu45z 
docker-composeのネットワークをhost直結に修正しました。
レビューお願いします。

chore: docker compose network mode host

---

projects/faucet/jpyx/deploy.sh

fix: faucet backend api deploy script

---

projects/telescope-extension/src/view/app.component.html

@KimuraYu45z 
レビューお願いします。
telescope側にはあるけれど、botany側にはないサイドナビリンクや、表記が大文字小文字異なるものを、telescope側の実装にあわせて揃えたものとなります。

feat: add side nav link gov and fix name

---

projects/telescope-extension/src/app/faucet/faucet.component.html
projects/telescope-extension/src/app/faucet/faucet.component.ts
projects/telescope-extension/src/app/faucet/faucet.module.ts
projects/telescope-extension/src/view/faucet/faucet.component.html
projects/telescope-extension/src/view/faucet/faucet.component.ts

close #84 
@KimuraYu45z 
レビューお願いします。
Faucetのリクエストが成功しているかどうかを、残高の変化をポーリングして判断し、状態をSnackBarとSpinnerで表示する修正を加えました。
ロジックはまだかなり汚く、イレギュラーなパターンではバグもありそうなレベル感ですが、いったん以下のようにローカルで動作確認できたので、これでレビューお願いしたいと思います。

feat: monitor balances after faucet requested

---

angular.json
package.json
projects/telescope-extension/editions/eurx/Dockerfile
projects/telescope-extension/editions/jpyx/Dockerfile

https://github.com/lcnem/botany/issues/86

feat: new basehref

---

.github/workflows/ci-docker-botany-pricefeed.yml
.github/workflows/ci-docker-telescope-eurx.yml
.github/workflows/ci-docker-telescope-jpyx.yml
projects/telescope-extension/editions/eurx/Dockerfile
projects/telescope-extension/editions/jpyx/Dockerfile

@KimuraYu45z cc: @Senna46 @taro04 
Dockerイメージのビルドで、npm ci時にコケている問題の解決を意図して加える修正です。
レビューお願いします。

fix: dockerfile

---

projects/telescope-extension/editions/jpyx/config.js
projects/telescope-extension/src/app/app.component.ts

close #102 
@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。

fix: faucet link and config

---

common/package-lock.json
package-lock.json
package.json
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/cdp.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdps.component.ts
projects/telescope-extension/src/app/utils/function.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdps.component.ts

@KimuraYu45z 
botany-client v0.3.7 -> v0.4.0 の対応です。
レビューお願いします。

chore: bumps botany client v040

---

projects/faucet/jpyx/nginx.conf
projects/telescope-extension/src/app/models/faucets/faucet.infrastructure.service.ts
projects/telescope-extension/src/app/models/faucets/faucet.model.ts
projects/telescope-extension/src/app/pages/faucet/faucet.component.html
projects/telescope-extension/src/app/pages/faucet/faucet.component.ts
projects/telescope-extension/src/app/views/faucet/faucet.component.html
projects/telescope-extension/src/app/views/faucet/faucet.component.ts

#100 
@YasunoriMATSUOKA さんご確認お願いいたします。

WIP fix: refactor faucet loading

---

projects/telescope-extension/src/app/models/keys/key-select.guard.ts
projects/telescope-extension/src/app/models/keys/key.infrastructure.service.ts
projects/telescope-extension/src/app/models/keys/key.store.service.ts

@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
telescopeの以下の修正と同様の修正です。
https://github.com/lcnem/telescope/pull/154

feat: key select dialog bug fix

---

projects/pricefeed/package-lock.json
projects/pricefeed/package.json
projects/pricefeed/src/clients/ccxt.ts
projects/pricefeed/src/price-oracle.ts

理論的には正しい修正です
ccxtなおして動作検証したいが。。。

fix: pricefeed sequence

---

projects/telescope-extension/src/app/models/cdps/cdp.application.service.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdps.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/clear/clear.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/deposit/deposit.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/issue/issue.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/withdraw/withdraw.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdps.component.html

@KimuraYu45z cc: @Senna46 @taro04 
レビューお願いします。
collateralTypeを指定すべき箇所にdenomが指定されていた問題の修正と、ルーティング関連の修正を行いました。
この修正の結果、createして、createされたCDPを表示して、そのページ内リンクからdeposit, withdraw, issue, clearページへ遷移する機能までは実装できたはずという認識です。
deposit, withdraw, issue, clearはまだ詳細にデバッグできていませんが、一旦、これで、デバッグすべきページが一通り表示できる状態になったと思うので、この状態でマージしておきたいと思っています。
確認お願いします。

fix: routing collateral type

---

projects/telescope-extension/src/app/views/app.component.html
projects/telescope-extension/src/styles.css

[https://github.com/lcnem/telescope/pull/193](https://github.com/lcnem/telescope/pull/193)と同様の修正です。
お手数ですが、ご確認お願い致します。

feat: adjust icon in sidenav to center

---

projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
projects/telescope-extension/src/app/pages/auction/auctions/auctions.component.ts

@Senna46 
現在以下プルリクで実装進めてくださっている中で、変数名の名前の付け方等、より具体的な名前がついている方が可読性が高く、後々メンテナンスしやすくなるのではないかと感じたため、自分だったらこう名付けるかなといった変数名の変更をプルリクにまとめました。(一部、未使用の変数を、こういう風に使用する意図だったのだろうと判断して使うように修正したりもしています。)
https://github.com/lcnem/botany/pull/136
内容確認の上、もし問題無ければ、大村さんにてこちらのプルリクをマージして、引き続き上記リンクのプルリクで作業進めてくださればと思います。
よろしくお願いします。
cc: @KimuraYu45z 
もし違和感あれば、ご指摘もらえると助かります。

chore: fix auction component args name

---

projects/telescope-extension/src/app/models/cdps/cdp.application.service.ts

close #145 
CDPがエラー検出できない問題の修正
Auction同様にエラーを抽出してます。

fix: cdp err detected

---

projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/full/config.js
projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/full/deploy.sh
projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/light/config.js
projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/light/deploy.sh
projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/standard/config.js
projects/telescope-extension/editions/jpyx/launch/jpyx-4-test/standard/deploy.sh

@KimuraYu45z 
chain-id変更したら、こちらにも変更が必要になることが認識漏れていました。
すみませんが、取り急ぎレビューお願いします。
実質的な差分は以下コミットです。
https://github.com/lcnem/botany/pull/147/commits/5f92da7e456258a2e096fbe3eb19a9962d6680ab

feat: add new network config jpyx 4 test

---

.github/workflows/deploy-botany-client-npm-publish.yml

@KimuraYu45z 
レビューお願いします。
botany-clientのnpm publishのCDをGitHub Actionsで実装しました。
cosmos-client-tsの内容をコピペして、botany-clientの既存のCIのスクリプトやパスに合わせて若干修正しました。

feat: cd of botany client npm publish with github actions

---

common/package-lock.json
projects/telescope-extension/src/app/models/auctions/auction.application.service.ts
projects/telescope-extension/src/app/models/auctions/auction.infrastructure.service.ts
projects/telescope-extension/src/app/models/auctions/auction.service.ts
projects/telescope-extension/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.html
projects/telescope-extension/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
projects/telescope-extension/src/app/views/auction/auctions/auction/place-bid/place-bid.component.html
projects/telescope-extension/src/app/views/auction/auctions/auction/place-bid/place-bid.component.ts

@KimuraYu45z 
レビューお願いします。
auctionに、simulate追加して、手数料設定適切に行えるよう修正した内容です。
デバッグして動作確認済です。

feat: add simulate request to auction place bid and fix gas and fee

---

projects/botany-client/package-lock.json
projects/botany-client/package.json

@KimuraYu45z 
レビューお願いします。
cosmos-client-tsのバージョンアップに伴い、botany-clientもバージョンアップしておくという内容です。
- bumps cosmos-client from v0.44.3 to v0.44.4
- bumps botany-client from v0.44.0 to v0.44.1

feat: bumps cosmos-client-ts on botany-client

---

projects/pricefeed/docker-compose.yml
projects/telescope-extension/editions/ununifi/docker-compose.yml

@KimuraYu45z 
レビューお願いします。
pricefeed, telescope-extensionについて、コンテナに明示的に名前をつけていなかったので、他と揃えて名前を付けました。

chore: add container name

---

package-lock.json
package.json
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/full/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/full/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/light/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/light/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/standard/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-5-test/standard/deploy.sh
projects/telescope-extension/src/app/models/auctions/auction.infrastructure.service.ts
projects/telescope-extension/src/app/models/cdps/cdp.infrastructure.service.ts
projects/telescope-extension/src/app/pages/auction/auction.component.ts
projects/telescope-extension/src/app/pages/auction/auctions/auction/auction.component.ts
projects/telescope-extension/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
projects/telescope-extension/src/app/pages/auction/auctions/auctions.component.ts
projects/telescope-extension/src/app/pages/cdp/cdp.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/cdp.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/clear/clear.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/deposit/deposit.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/issue/issue.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/withdraw/withdraw.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdps.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/create/create.component.ts
projects/telescope-extension/src/app/utils/function.ts
projects/telescope-extension/src/app/utils/stream.ts
projects/telescope-extension/src/app/views/auction/auctions/auction/auction.component.ts
projects/telescope-extension/src/app/views/auction/auctions/auction/place-bid/place-bid.component.ts
projects/telescope-extension/src/app/views/auction/auctions/auctions.component.ts
projects/telescope-extension/src/app/views/cdp/cdp.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/create/create.component.ts

fix: telescope extension to bumps ununifi client

---

README.md
projects/pricefeed/launch/ununifi-5-test/.env.example
projects/pricefeed/launch/ununifi-6-test/.env.example
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/full/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/full/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/light/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/light/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/standard/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/standard/deploy.sh

@KimuraYu45z 
レビューお願いします。
chain-id=ununifi-6-testの明日ローンチ予定のパブリックテストネットへの設定ファイルやデプロイスクリプト等の修正対応です。

feat: ununifi-6-test

---

projects/main/src/app/views/home/home.component.html

@KimuraYu45z 
レビューお願いします。
Contributionのcosmos-client-ts以外を削除しようということになったので、修正しました。

fix: remove unnecessary contributions

---

projects/main/src/app/views/home/home.component.html

@KimuraYu45z 
レビューお願いします。
フォームのリンクをNeukindから指定頂いたものに差し替えました。

fix: form link of landing page

---

projects/telescope-extension/src/app/models/auctions/auction.application.service.ts
projects/telescope-extension/src/app/models/cdps/cdp.application.service.ts

@KimuraYu45z 
レビューお願いします。
hotfix https://github.com/UnUniFi/utils/pull/178 のdevelopへの反映です。

feat: add loading dialog to simulation

---

.github/workflows/action-trigger-docker-telescope-ununifi-private-test.yml
.github/workflows/docker-telescope-ununifi-private-test.yml
projects/telescope-extension/editions/ununifi/Dockerfile-private-test

@KimuraYu45z 
レビューお願いします。
dockerfile内の指定で cauchye/telescopeのdockerについて、 latestタグとtestタグを、パブリックテストネット用のイメージとプライベートテストネット用のイメージで分ける必要があったため、Dockerfileの追加や修正と、CDの修正を行いました。

fix: cd and dockerfile of telescope ununifi on private test

---

projects/telescope-extension/src/app/app.component.html
projects/telescope-extension/src/app/app.component.ts
projects/telescope-extension/src/app/views/app.component.html
projects/telescope-extension/src/app/views/app.component.ts
projects/telescope-extension/src/app/views/toolbar/toolbar.component.html
projects/telescope-extension/src/app/views/toolbar/toolbar.component.ts

[https://github.com/UnUniFi/utils/issues/174](https://github.com/UnUniFi/utils/issues/174)の修正です。
toolbar.htmlの中身が空だったことが原因でした。
基本的には今回の検索バーUX向上の実装を展開しています。
telescopeでrouterを使ってページ遷移しているところは、`location.href`で実装しました。
ローカルでは動作確認できていませんが、飛ぼうとするurlを見るに、
問題なさそうだと思っています。
合わせて、ドロワー展開するアイコンが透明になっている件、
合わせて修正しています。[https://github.com/CauchyE/telescope/pull/236](https://github.com/CauchyE/telescope/pull/236)
ご確認お願い致します。

Revival serch box

---

projects/telescope-extension/src/app/app.component.html
projects/telescope-extension/src/app/app.component.ts
projects/telescope-extension/src/app/views/app.component.html
projects/telescope-extension/src/app/views/app.component.ts
projects/telescope-extension/src/app/views/toolbar/toolbar.component.html
projects/telescope-extension/src/app/views/toolbar/toolbar.component.ts

@taro04 
レビュー(というよりもどちらかという)と今後の作業の進め方について、以下の確認をお願いします。(既にプルリク作成済のものはそのままでOKです。)
既にmainブランチにマージしたプルリク( https://github.com/UnUniFi/utils/pull/183 )のように、mainに直接修正を加えるhotfix的な変更については、developにも同様に都度都度反映していく想定で考えています。
Git Flow( https://dev.classmethod.jp/articles/introduce-git-flow/ )からrelease branchesだけ除いたイメージとご理解ください。
mainブランチ、developブランチはそれぞれ以下ネットワークと対応させるよう運用する予定です。
main ... public testnet, Chain ID = ununifi-6-test
develop ... private testnet, Chain ID = ununifi-7-private-test ... 現時点では未ローンチ
つのださんにこれからお願いするタスクは、しばらくは多くの場合、mainブランチを基点に直接修正を加えるhotfix的な変更になると思うので、その場合はブランチ名を hotfix/hogehogeのような名前に統一してください。hogehogeの箇所はこれまでと同様、変更内容がわかるよう適宜名前つけて頂ければOKです。お手数ですがよろしくお願いします。(そうでない場合はその旨明示して作業お願いするようにします。)
private testnetだけでまず試したい大きな機能追加や、影響範囲の大きな変更等については、developブランチを基点にfeature/fugafugaのような名前に統一してくだ …

feat: add search box

---

common/package-lock.json
package-lock.json
package.json
projects/telescope-extension/src/app/views/auction/auction.module.ts
projects/telescope-extension/src/app/views/auction/auctions/auction/auction.module.ts
projects/telescope-extension/src/app/views/auction/auctions/auction/place-bid/place-bid.module.ts
projects/telescope-extension/src/app/views/auction/auctions/auctions.module.ts
projects/telescope-extension/src/app/views/cdp/cdp.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/clear/clear.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/deposit/deposit.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/issue/issue.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/withdraw/withdraw.module.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdps.module.ts
projects/telescope-extension/src/app/views/home/home.module.ts
projects/telescope-extension/src/app/views/keys/key-select-dialog/key-select-dialog.module.ts
projects/telescope-extension/src/app/views/toolbar/toolbar.module.ts
projects/telescope-extension/src/app/views/view.module.ts

@KimuraYu45z @taro04 
以下プルリク(レビュー済)と同じ内容なので、CI通ってコンフリクト無ければそのままレビュー無しでマージします。
https://github.com/UnUniFi/utils/pull/175

feat: delete angular-flex-layout

---

projects/telescope-extension/src/app/views/auction/auction.component.html
projects/telescope-extension/src/app/views/auction/auctions/auction/auction.component.html
projects/telescope-extension/src/app/views/cdp/cdp.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.component.html

@KimuraYu45z @taro04 
以下プルリク(レビュー済)と同じ内容なので、CI通ってコンフリクト無ければそのままレビュー無しでマージします。
https://github.com/UnUniFi/utils/pull/184

feat: delete last element divider and improve appearance of numbers and dates

---

projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/full/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/light/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-6-test/standard/config.js

@KimuraYu45z 
レビューお願いします。
bのノードだけでなく、aのノードでもFaucetを有効化した状況にあわせて、Telescopeのconfigファイルを修正したという内容です。

hotfix: enable faucet not only b but a

---

projects/pricefeed/launch/ununifi-7-private-test/.env.example
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/docker-compose.yml
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/full/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/full/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/light/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/light/deploy.sh
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/standard/config.js
projects/telescope-extension/editions/ununifi/launch/ununifi-7-private-test/standard/deploy.sh

@KimuraYu45z 
レビューお願いします。
telescopeとpricefeedのununifi-7-private-test向けのデプロイスクリプトや設定ファイルや環境ファイルの雛型等を追加しました。

feat: ununifi 7 private test

---

projects/pricefeed/src/price-oracle.ts

https://github.com/UnUniFi/utils/pull/194

fix: hotfix pricefeed fee

---

projects/faucet/deploy.sh
projects/faucet/docker-compose.yml
projects/faucet/nginx.conf

@KimuraYu45z 
レビューお願いします。
faucetをutilsに移す件ですが、developとmainでfaucetの対象資産を増やした分の変更があったので、mainブランチへのPRとは別に別途実装したという状況です。

feat: move faucet to this repository develop

---

projects/faucet/deploy.sh
projects/faucet/docker-compose.yml
projects/faucet/nginx.conf

@KimuraYu45z 
レビューお願いします。
faucetをutilsに移す件です。

feat: move faucet to this repository

---

projects/faucet/deploy.sh

As the location of faucet repository moved, I fixed utils/projects/faucet/deploy.sh.

fix: the location of faucet repo

---

projects/faucet/deploy.sh
projects/faucet/docker-compose.yml

I fixed faucet/deploy.sh and faucet/docker-compose.yml to mount the required binary files.
But, this implementation is not definitely the best.
I will open an issue for this later.

fix: docker mount

---

projects/main/src/app/views/home/home.component.html

@mkXultra 
plz review 🙏 
- Fix: lp token distribution
- Fix: remove unnecessary section
Before Screenshot
After Screenshot

fix: lp token distribution

---

projects/telescope-extension/src/app/pages/cdp/cdps/cdp/clear/clear.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/issue/issue.component.ts

close #236 
close #237 
Fixed Denom issues in Issue and Clear.

v0.45.1 support for /ununifi/cdp  issue clear

---

projects/telescope-extension/src/app/pages/cdp/cdps/cdp/cdp.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/clear/clear.component.html
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/clear/clear.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/deposit/deposit.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/issue/issue.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/cdp/withdraw/withdraw.component.ts
projects/telescope-extension/src/app/pages/cdp/cdps/create/create.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/cdp.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/clear/clear.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/clear/clear.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/deposit/deposit.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/deposit/deposit.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/issue/issue.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/issue/issue.component.ts
projects/telescope-extension/src/app/views/cdp/cdps/cdp/withdraw/withdraw.component.html
projects/telescope-extension/src/app/views/cdp/cdps/cdp/withdraw/withdraw.component.ts

@YasunoriMATSUOKA 
Please review.
To do : 
- Reduce Rest API access load by stopping continuous Rest API access on timer.
-->  delete timer Observable
- To prohibit the user from sending transactions, display the loading is during data acquisition.
-->  add progress spiner in html

fix: reduce API load on some page and add progress spinner

---

projects/pricefeed/src/price-oracle.ts

Newly supported ubtc:usd market id.

add ubtc:usd pair for supporting marketId

---

projects/pricefeed/.env.template
projects/pricefeed/src/price-oracle.ts

support `ubtc:uusdc` and `ubtc:uusdc:30` market id pricefeed to feed `ubtc:uusdc` price in the chain side

support ubtc:uusdc market id

---

projects/pricefeed/.env.template
projects/pricefeed/src/price-oracle.ts

made default values relating to gas price 0.

make default gas price 0

---

projects/pricefeed/README.md
projects/pricefeed/package-lock.json
projects/pricefeed/package.json
projects/pricefeed/src/constants/collection.ts
projects/pricefeed/src/domain/market-price.ts
projects/pricefeed/src/index.ts
projects/pricefeed/src/post-price.ts
projects/pricefeed/src/price-oracle.ts
projects/pricefeed/src/price-stargaze.ts
projects/telescope-extension/src/app/models/tx-common/tx-common.infrastructure.service.ts

Add stargaze NFT Collection Prices 
Reference: https://github.com/cosmos-client/cosmwasm-ts/blob/v0.40.1/src/rest/wasm/instantiate-contract.spec.ts

feat: pricefeed-stargaze
